### PR TITLE
Update tutorial on reaction rate parameterizations

### LINKED ISSUE #212: Teach input_data to see parameters in Python tutorial
Please update https://cantera.org/tutorials/python-tutorial.html to teach about the new `input_data` property as the way to see parameters. See https://github.com/Cantera/cantera/issues/1329.

### PR DESCRIPTION
**Pull request by ischoegl**
Update portion of tutorial covering reaction rates

Closes #212

### CODE REVIEW

**Comment by ischoegl** [comment]
@bryanwweber ... is there a way to get Sphinx to recognize `:py:attr:`ReactionRate.input_data`? (it is a property) ... as far as I am aware, it is a legitimate tag, but the website apparently doesn't support it ...

**Comment by bryanwweber** [comment]
@ischoegl Can I suggest we defer fixing that until after #209, #210, and #211 land? I suspect it's an issue with the Nikola/Sphinx bridge, and hopefully once we get everything into Sphinx it'll be easier.

**Comment by ischoegl** [comment]
@bryanwweber ... np. I skipped the link for the time being, but left a note.

**Review by bryanwweber — APPROVED** [review]
Thanks for the quick fix @ischoegl!

**Pull request merged**
