### PR TITLE
Fix link formatting in reST

### PR DESCRIPTION
**Pull request by ischoegl**
Switch Markdown to reST syntax ...

### CODE REVIEW

**Review by bryanwweber — APPROVED** [review]

**Comment by bryanwweber** [comment]
I'm not sure what the status of `testing` is right now with respect to merged PRs, so I'm not merging this pending a check on that. @ischoegl feel free to merge if this is good to go.

**Comment by ischoegl** [comment]
@bryanwweber ... thanks! I'm not familiar enough with how `testing` gets treated at this point, so I want to make sure the fix is applied as appropriate (this change doesn't apply to 2.5.1). Fwiw, I assume that `testing` will replace `main` once 2.6.0 is released?

**Comment by bryanwweber** [comment]
> Fwiw, I assume that `testing` will replace `main` once 2.6.0 is released?

That's not the usual purpose of the testing branch, but I think that's the plan for this release. My comment was saying that I know there have been several PRs targeting the `testing` branch lately, and I'm not sure how this change relates to those PRs. I suppose since there are no merge conflicts, `testing` is up-to-date with changes affecting this line, but I wasn't sure...

**Comment by ischoegl** [comment]
Thanks for the clarification! This PR is based on `testing`, so I think this is ok then.

**Pull request merged**
