### PR TITLE
Update SCons configuration options to version 2.5.1

### LINKED ISSUE #159: Scons configuration options page still references Cantera 2.4
The page listing [configuration options](https://cantera.org/compiling/config-options.html#scons-config) still refers to Cantera 2.4. This would be resolved by #26.

### PR DESCRIPTION
**Pull request by ischoegl**
Update `config-options.rst` to Cantera version 2.5.1

Fixes #159

File content was generated using `scons2rst.py` script (see Cantera/cantera#1136), with minor manual edits.

### CODE REVIEW

**Comment by ischoegl** [comment]
I also updated the `SConstruct` option documentation for the current development version, which is 'cut&paste' from output. Once Cantera/cantera#1136 is merged, the code below `Options` will be automatically available in the `dev` folder (as generated by `scons2rst.py` when the main repo is updated). This can be copied into the toc tree before the build, and included in `config-options-dev.rst`.

I can drop 305a791 here if the update for the development version should happen at a later point.

**Comment by ischoegl** [comment]
:tada: ... this appears to be working.

The solution builds on Cantera/cantera#1137 and Cantera/cantera#1142 (oops).

**Comment by ischoegl** [comment]
@bryanwweber / @speth ... now that the automatic generation from reST is working (including the newline :joy:) I copied over the system-dependent options from the previous `-dev` version to the current 2.5.1 documentation. So I _think_ #159 is now fully addressed.

**Review by speth — APPROVED** [review]
Looks good to me. Thanks, @ischoegl.

**Pull request merged**
