### PR TITLE
Add license.txt

### PR DESCRIPTION
**Pull request by petrkle**
Add license.txt on web #42

### CODE REVIEW

**Comment by bryanwweber** [comment]
Hi! 👋 Thanks for making this pull request. I think it would be better to explicitly list all the files to be copied, rather than relying on copying the whole folder.

**Comment by bryanwweber** [comment]
Hi @petrkle! Do you plan to update this pull request for the change I mentioned?

**Comment by petrkle** [comment]
Sorry, I'am not so familiar with Nikola. If I try copy one file (not directory) it end with error. You can close this PR.

**Comment by bryanwweber** [comment]
@petrkle Right, so this turns out to be a bit more complicated than I thought, plus we're going to be adding more files, so I'm just going to merge this. Thank you for your contribution!

**Pull request merged**
