### PR TITLE
cantera-website

### PR DESCRIPTION
**Pull request by jithendra-roy**
issues #53 and #45 are modified

### CODE REVIEW

**Comment by bryanwweber** [comment]
Hi! Thank you for this contribution. Just a few comments.

1. I'm actually working to fix the table of contents issue in a separate branch as part of refactoring the example generating code. Can you please drop those commits?
2. Can you provide a screenshot of the result of adding the GitHub link?
3. Can you troubleshoot why the build on Travis CI is failing?

Thanks!

**Comment by jithendra-roy** [comment]
52151476_367885060472757_4646251631757754368_n

52983128_627579357691076_3886079477343584256_n

**Comment by bryanwweber** [comment]
OK, now I see where you put that. Instead of in that card, I think it would be good to add a new section, so the home page looks like

Connect with Cantera    |   How is Cantera supported
Google Group                 |   Existing text about NumFOCUS
GitHub                             |   Existing picture

So basically, have two columns on the bottom row with the Connect/contact information on the left and the NumFOCUS information on the right. The code will look very similar to the 4 columns near the top of the page, but obviously only with two columns instead of 4.

To get a better preview of the website, you can do

`nikola build && nikola serve -b`

which will build the site and open a browser to show how the site will work. To stop that, just push CTRL+C in the terminal

**Comment by bryanwweber** [comment]
Hi @jithendra-roy I see you updated the code on the index. Could please post another screenshot with the CSS correct? Please see my earlier comment for other changes as well.

**Comment by nishikeshKardak** [comment]
Hello, @jithendra-roy are you still working on this issue??

**Comment by jithendra-roy** [comment]
I did the necessary changes but there is a problem with deployment that I am still figuring it out.

**Comment by bryanwweber** [comment]
The problems with the Travis CI build are being fixed in #58

**Pull request closed without merging**
